// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHwIe-jPBIhhasGeeGoqkLSCefe3BvgfM',
    appId: '1:1099400061173:web:814e393af6b48cb22325bc',
    messagingSenderId: '1099400061173',
    projectId: 'netflix-clone-project-648c1',
    authDomain: 'netflix-clone-project-648c1.firebaseapp.com',
    storageBucket: 'netflix-clone-project-648c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFeneQJMwAOdeoI-0NzXmmE2jEWy0CEYA',
    appId: '1:1099400061173:android:0a7af0e7725158772325bc',
    messagingSenderId: '1099400061173',
    projectId: 'netflix-clone-project-648c1',
    storageBucket: 'netflix-clone-project-648c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl29H_3v9e7aM2W_f0hdxWou1FFgXU_Fs',
    appId: '1:1099400061173:ios:5bc81762b5d96f272325bc',
    messagingSenderId: '1099400061173',
    projectId: 'netflix-clone-project-648c1',
    storageBucket: 'netflix-clone-project-648c1.appspot.com',
    iosClientId: '1099400061173-309uib0hc9dus3ieb0amnpsm7dvhrsdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNetflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl29H_3v9e7aM2W_f0hdxWou1FFgXU_Fs',
    appId: '1:1099400061173:ios:fb6493262dfe3dbb2325bc',
    messagingSenderId: '1099400061173',
    projectId: 'netflix-clone-project-648c1',
    storageBucket: 'netflix-clone-project-648c1.appspot.com',
    iosClientId: '1099400061173-curh835fkp17n5n7n3hrpcpaulfkhepn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNetflix.RunnerTests',
  );
}

